#cloud-config
# Cloud-init конфигурация для Control Plane нод
# Автор: AI-агент VM Preparation Specialist
# Дата: 2025-01-27
# Версия: 1.0

# Основные настройки
hostname: ${hostname}
fqdn: ${hostname}.${domain}

# Настройки пользователей
users:
  - name: k8s-admin
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    groups: [adm, systemd-journal, docker]
    ssh_authorized_keys:
      - ${ssh_public_key}
    home: /home/k8s-admin
    create_home: true

# Настройки SSH
ssh_pwauth: false
disable_root: true
ssh_deletekeys: true
ssh_genkeytypes: ['rsa', 'ecdsa', 'ed25519']

# Настройки сети
network:
  config: disabled

# Файлы для создания
write_files:
  # Настройка статического IP
  - path: /etc/netplan/01-static-ip.yaml
    content: |
      network:
        version: 2
        ethernets:
          ens192:
            addresses: [${ip_address}/${subnet_mask}]
            gateway4: ${gateway}
            nameservers:
              addresses: [${dns_servers}]
            dhcp4: false
            dhcp6: false
    permissions: '0644'
    owner: root:root

  # Настройка kubelet для containerd
  - path: /etc/default/kubelet
    content: |
      KUBELET_EXTRA_ARGS="--container-runtime=remote --container-runtime-endpoint=unix:///var/run/containerd/containerd.sock --runtime-cgroups=/system.slice/containerd.service"
    permissions: '0644'
    owner: root:root

  # Настройка containerd
  - path: /etc/containerd/config.toml
    content: |
      version = 2
      root = "/var/lib/containerd"
      state = "/run/containerd"

      [grpc]
        address = "/run/containerd/containerd.sock"
        uid = 0
        gid = 0

      [ttrpc]
        address = "/run/containerd/containerd.sock.ttrpc"
        uid = 0
        gid = 0

      [debug]
        address = ""
        uid = 0
        gid = 0
        level = ""

      [metrics]
        address = ""
        grpc_histogram = false

      [cgroup]
        path = ""

      [timeouts]
        "io.containerd.timeout.shim.cleanup" = "5s"
        "io.containerd.timeout.shim.load" = "5s"
        "io.containerd.timeout.shim.shutdown" = "3s"
        "io.containerd.timeout.task.state" = "2s"

      [plugins]
        [plugins."io.containerd.gc.v1.scheduler"]
          pause_threshold = 0.02
          deletion_threshold = 0
          mutation_threshold = 100
          schedule_delay = "0s"
          startup_delay = "100ms"
        [plugins."io.containerd.grpc.v1.cri"]
          disable_tcp_service = true
          stream_server_address = "127.0.0.1"
          stream_server_port = "0"
          stream_idle_timeout = "4h0m0s"
          enable_selinux = false
          selinux_category_range = 1024
          sandbox_image = "registry.k8s.io/pause:3.9"
          stats_collect_period = 10
          systemd_cgroup = true
          enable_tls_streaming = false
          max_container_log_line_size = 16384
          disable_cgroup = false
          disable_apparmor = false
          restrict_oom_score_adj = false
          max_concurrent_downloads = 3
          disable_proc_mount = false
          unset_seccomp_profile = ""
          tolerate_missing_hugetlb_controller = true
          disable_hugetlb_controller = true
          ignore_image_defined_volumes = false
          [plugins."io.containerd.grpc.v1.cri".containerd]
            snapshotter = "overlayfs"
            default_runtime_name = "runc"
            no_pivot = false
            disable_snapshot_annotations = true
            discard_unpacked_layers = false
            [plugins."io.containerd.grpc.v1.cri".containerd.runtimes]
              [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc]
                runtime_type = "io.containerd.runc.v2"
                runtime_engine = ""
                runtime_root = ""
                privileged_without_host_devices = false
                base_runtime_spec = ""
                [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc.options]
                  BinaryName = "runc"
                  Root = ""
                  CriuImagePath = ""
                  CriuPath = ""
                  CriuWorkPath = ""
                  SystemdCgroup = true
        [plugins."io.containerd.internal.v1.opt"]
          path = "/var/lib/containerd/io.containerd.internal.v1.opt"
        [plugins."io.containerd.internal.v1.restart"]
          interval = "10s"
        [plugins."io.containerd.metadata.v1.bolt"]
          content_sharing_policy = "shared"
        [plugins."io.containerd.monitor.v1.cgroups"]
          no_prometheus = false
        [plugins."io.containerd.runtime.v1.linux"]
          shim = "containerd-shim"
          runtime = "runc"
          runtime_root = ""
          no_shim = false
          shim_debug = false
        [plugins."io.containerd.runtime.v2.task"]
          platforms = ["linux/amd64"]
        [plugins."io.containerd.service.v1.diff-service"]
          default = ["walking"]
        [plugins."io.containerd.snapshotter.v1.devmapper"]
          root_path = ""
          pool_name = ""
          base_image_size = ""
          async_remove = false
    permissions: '0644'
    owner: root:root

  # Настройка sysctl для Kubernetes
  - path: /etc/sysctl.d/99-kubernetes.conf
    content: |
      # IP forwarding для pod networking
      net.ipv4.ip_forward = 1
      net.ipv6.conf.all.forwarding = 1

      # Bridge netfilter для CNI
      net.bridge.bridge-nf-call-iptables = 1
      net.bridge.bridge-nf-call-ip6tables = 1

      # Дополнительные настройки для производительности
      net.core.somaxconn = 32768
      net.core.netdev_max_backlog = 5000
      net.ipv4.tcp_max_syn_backlog = 8192
    permissions: '0644'
    owner: root:root

  # Настройка модулей ядра
  - path: /etc/modules-load.d/kubernetes.conf
    content: |
      overlay
      br_netfilter
    permissions: '0644'
    owner: root:root

  # Настройка timezone
  - path: /etc/timezone
    content: |
      UTC
    permissions: '0644'
    owner: root:root

  # Настройка firewall для Control Plane
  - path: /etc/ufw/before.rules
    content: |
      # Kubernetes Control Plane ports
      -A ufw-before-input -p tcp --dport 6443 -j ACCEPT
      -A ufw-before-input -p tcp --dport 2379:2380 -j ACCEPT
      -A ufw-before-input -p tcp --dport 10250 -j ACCEPT
      -A ufw-before-input -p tcp --dport 10251 -j ACCEPT
      -A ufw-before-input -p tcp --dport 10252 -j ACCEPT
      -A ufw-before-input -p tcp --dport 10259 -j ACCEPT
      -A ufw-before-input -p tcp --dport 10257 -j ACCEPT
    permissions: '0644'
    owner: root:root

# Команды для выполнения
runcmd:
  # Применить сетевые настройки
  - netplan apply

  # Загрузить модули ядра
  - modprobe overlay
  - modprobe br_netfilter

  # Применить sysctl настройки
  - sysctl --system

  # Настроить timezone
  - timedatectl set-timezone UTC

  # Включить и запустить containerd
  - systemctl enable containerd
  - systemctl start containerd

  # Включить kubelet (но не запускать до kubeadm init)
  - systemctl enable kubelet

  # Перезагрузить systemd
  - systemctl daemon-reload

  # Очистить кэш пакетов
  - apt clean

  # Создать директорию для SSH ключей
  - mkdir -p /home/k8s-admin/.ssh
  - chmod 700 /home/k8s-admin/.ssh
  - chown k8s-admin:k8s-admin /home/k8s-admin/.ssh

  # Настроить firewall для Control Plane
  - ufw --force enable
  - ufw allow ssh
  - ufw allow 6443/tcp
  - ufw allow 2379:2380/tcp
  - ufw allow 10250/tcp
  - ufw allow 10251/tcp
  - ufw allow 10252/tcp
  - ufw allow 10259/tcp
  - ufw allow 10257/tcp

# Настройки для первого запуска
cloud_init_modules:
  - migrator
  - seed_random
  - bootcmd
  - write-files
  - growpart
  - resizefs
  - disk_setup
  - mounts
  - set-passwords
  - ssh

cloud_final_modules:
  - package-update-upgrade-install
  - runcmd
  - byobu
  - landscape
  - lxd
  - puppet
  - chef
  - salt-minion
  - mcollective
  - disable-ec2-metadata
  - final-message
  - power-state-change

# Настройки для финального сообщения
final_message: |
  ==========================================
  🎉 Kubernetes Control Plane VM готова!
  ==========================================

  Хост: ${hostname}
  IP: ${ip_address}
  Пользователь: k8s-admin

  Следующие шаги:
  1. Проверить подключение: ssh k8s-admin@${ip_address}
  2. Инициализировать кластер: kubeadm init --control-plane-endpoint=${api_vip}
  3. Настроить kubeconfig: mkdir -p ~/.kube && cp /etc/kubernetes/admin.conf ~/.kube/config
  4. Установить CNI: kubectl apply -f <cni-manifest>

  ==========================================

# Настройки для отключения автоматических обновлений
package_update: false
package_upgrade: false
package_reboot_if_required: false

# Настройки для отключения snap
snap:
  commands:
    - snap refresh --time
    - snap set system refresh.timer=fri,5:00-9:00
    - snap set system refresh.hold="$(date --date='next Friday 5:00' --iso-8601=seconds)"

# Настройки для отключения автоматических обновлений
apt:
  sources:
    kubernetes:
      source: "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.31/deb/ /"
      keyid: "B53DC80D13EDEF05"
  packages:
    - kubelet=1.31.2-1.1
    - kubeadm=1.31.2-1.1
    - kubectl=1.31.2-1.1
  conf: |
    APT {
      Get {
        Assume-Yes "true";
        Fix-Broken "true";
      };
    }
